name: code-freeze-thursday
run-name: Label PRs on Thursday
on:
  pull_request_target:
    branches:
     - main
  schedule:
    - cron: '* * * * 6'  # Every Thursday./ Actual test: Friday
jobs:
  label-every-pr:
    permissions:
        contents: read
        pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: n